### ISSUE TITLE
Fast Bitstring.is_prefix

### ISSUE THREAD

**Issue by cmr** [xguerin/bitstring#16]
This would be handy. Currently I do the very inefficient

```ocaml
let is_prefix t ~prefix = String.is_prefix (of_string t) ~prefix:(of_string prefix)
```

**Comment by xguerin** [comment]
Agreed. Tracked here: https://bitbucket.org/thanatonauts/bitstring/issues/1/add-support-for-fast-bitstringis_prefix

**Comment by xguerin** [comment]
Done: https://bitbucket.org/thanatonauts/bitstring/commits/5de68418a677ab0fd06cfef217d1de9597c3a4bb
