### ISSUE TITLE
Release new version on opam to support 4.08 let* syntax.

### ISSUE THREAD

**Issue by dozzman** [xguerin/bitstring#21]
Hi Xavier,

Since cc482d3b7ba311613369500e6f10e395c41b61d0 has been merged would you help to create a new version on opam so it can be successfully installed from there? Maybe as version 3.1.2. Currently I'm having to pin the repository at this commit to have my code working.

I can drop a PR to update the opam config.

Dorian

**Comment by xguerin** [comment]
Sure. I am finalizing a few things with the migration back to GH. I’ll release a new version once I am done (sometimes next week at the latest).

**Comment by xguerin** [comment]
WIP: https://github.com/ocaml/opam-repository/pull/17227

**Comment by dozzman** [comment]
Awesome, will follow there
