### ISSUE TITLE
impossible to install ppx_bitstring and lwt_ppx

### ISSUE THREAD

**Issue by mbacarella** [xguerin/bitstring#25]
```
% opam install ppx_bitstring
The following actions will be performed:
  ⊘ remove    usb                     1.3.1            [uses lwt_ppx]
  ⊘ remove    ppx_deriving            4.5              [conflicts with ocaml-migrate-parsetree]
  ⊘ remove    lwt_ppx                 2.0.1            [conflicts with ocaml-migrate-parsetree]
  ⊘ remove    ppxfind                 1.4              [conflicts with ocaml-migrate-parsetree]
  ⊘ remove    ppx_tools_versioned     5.4.0            [conflicts with ocaml-migrate-parsetree]
  ↗ upgrade   ocaml-migrate-parsetree 1.8.0 to 2.1.0   [required by ppxlib]
  ↗ upgrade   ppxlib                  0.15.0 to 0.17.0 [required by ppx_bitstring]
  ∗ install   ppx_bitstring           4.0.0
```

ppx_bitstring depends on `"ppxlib" {build & >= "0.16.0" & < "0.18.0"}`

ppxlib >= 0.16.0 & < 0.18.0 depend on `"ocaml-migrate-parsetree" {>= "2.0.0"}`

However,

lwt_ppx depends on `"ocaml-migrate-parsetree" {>= "1.5.0" & < "2.0.0"}`

So, they're incompatible.

I note ppxlib 0.15.0 declares: `"ocaml-migrate-parsetree" {>= "1.5.0" & < "2.0.0"}`, which would satisfy lwt_ppx and ppx_bitstring seems to compile just fine with ppxlib 0.15.0, so perhaps change to that?

**Comment by xguerin** [comment]
I'll look into it.

**Comment by xguerin** [comment]
Should be fixed now.

**Comment by mbacarella** [comment]
Thanks! :party_parrot:
