### ISSUE TITLE
Release schedule for OCaml 4.06.0 compatible version of bitstring?

### ISSUE THREAD

**Issue by jgjl** [xguerin/bitstring#8]
Hi,

thank for your library! Bitstring gives OCaml a nice touch of Erlang, which is really cool :)

Do you have a schedule for releasing a OCaml 4.06.0 compatible version of it?
It would be great to know if I should wait or switch back to OCaml 4.05.0.

Thank you,

Jeremias

**Comment by xguerin** [comment]
Hey there,

`master/HEAD` is already there. It should work with `4.06.0` if you pin it. I have a more involved update in the making (`v3`) but that's gonna take a little bit more time.

**Comment by jgjl** [comment]
Ok, thank you for the quick reply!
